### Registro de usuario

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "ebe",
  "email": "ob@gmail.com",
  "password": "123456789",
  "telefono": "94549026",
  "about": "Fanatico del cine",
  "role_name": "usuario"
}

### Inicio de sesión

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "ob@gmail.com",
  "password": "123456789"
}

### Obtener publicaciones
GET http://localhost:3000/api/publicaciones
Accept: application/json

### Crear una nueva publicación
POST http://localhost:3000/api/publicaciones
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYjMyZGVjZmQyYjQ0NDA3YWJkYTZkM2IyMzZkYTJhNTAiLCJuYW1lIjoiZWJlIiwiaWF0IjoxNzU0MzcxOTU3LCJleHAiOjE3NTQzNzU1NTd9.JeAOt8UtWLuMWc376fldQTYGFj7oP5Zb71OOLR7aMHA

{
  "title": "Mi segundo post",
  "content_line1": "Contenido principal",
  "content_line2": "Más detalles opcionales",
  "image": "https://via.placeholder.com/150",
  "category_category_id": 1
}
